import { Inter } from "next/font/google";
import "@/styles/globals.css";
import type { Metadata } from "next";
import MyNavbarProvider from "@/components/MyNavbarProvider";
import { ToastContainer } from "react-toastify";
import Providers from "@/components/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`antialiased text-foreground bg-background ${inter.className}`}
    >
      <body className="min-h-screen antialiased">
        <Providers>
          <MyNavbarProvider />

          <div className="container max-w-7xl mx-auto h-full pt-12">
            {children}
          </div>
          <ToastContainer />
        </Providers>
      </body>
    </html>
  );
}
